name: BlockResetLite
version: '1.0-SNAPSHOT'
main: Refil.blockResetLite.BlockResetLite
api-version: '1.21'
authors: [ Refil ]
description: Something like MineResetLite but resets single blocks after a delay of time.
depend:
  - WorldGuard
  - FastAsyncWorldEdit